### ISSUE TITLE
【No.1】 CSS3实现一个扇形

### ISSUE THREAD

**Issue by xiqe** [xiqe/Interview-QA#1]
```css
.sector{
  display:inline-block;
  width:0;
  height:0;
  border-width:20px;
  border-style:solid;
  border-color:green transparent transparent;
  border-radius:20px;
}
```
